### ISSUE TITLE
Board 기간 만료 방식

### ISSUE THREAD

**Issue by gimhanul** [Bamdoliro/stupetition-server#37]
### ✨ Describe

Board 기간 만료를 status로 관리하지 않고 endDate를 설정해서 기간으로 쿼리해오는 게 더 좋을 것 같습니다.

### ✅ Tasks

- [ ] queryDsl 도입
- [x] endDate field 추가
- [x] 만들 때마다 createdAt + 설정한 기간으로 board 생성
- [x] query할 때 기간 validation
- [x] numberOfApprover 추가
