### ISSUE TITLE
부탁드립니다

### ISSUE THREAD

**Issue by SEOKKAMONI** [Bamdoliro/stupetition-server#39]
### ✨ Describe

- 동의하기와 댓글을 나눠주세요
- board/detail get 할때 이사람이 동의를 했는지 안했는지와 createdAt을 넘겨주세요
- 그리고 board/detail get 할때 댓글리스트를 가져올때 id 를 추가해주세요
- 자기 댓글 삭제 기능
- 댓글 쓰는 기능

### ✅ Tasks

- [x] 동의하기와 댓글을 나눠주세요
- [x] board/detail get 할때 이사람이 동의를 했는지 안했는지와 createdAt을 넘겨주세요
- [x] 그리고 board/detail get 할때 댓글리스트를 가져올때 id 를 추가해주세요
- [x] 자기 댓글 삭제 기능
- [x] 댓글 쓰는 기능
