### ISSUE TITLE
Excpetion 처리

### ISSUE THREAD

**Issue by gimhanul** [Bamdoliro/Stupetition-server#4]
### ✨ Describe

Exception 처리가 필요합니다.

### ✅ Tasks

- [x] Error Code 작성
- [x] StupetitionException 작성
- [x] Error Response dto 작성
- [x] global exception handler 작성
