### ISSUE TITLE
부탁드립니다

### ISSUE THREAD

**Issue by SEOKKAMONI** [Bamdoliro/stupetition-server#40]
### ✨ Describe

- comment 넘겨줄때 userId 도 넘겨주셔야합니다 -> 삭제 버튼 띄울지 말지
- 그러면 로그인 성공시 data 주는 값에 userId를 추가해주셔야합니다
- approve cors 에러 해결해주세엽
- comment data 넘겨줄떄 어드민이 쓴건지 학생이 쓴건지도 넘겨주세요
- 마이 청원 -> 내가올린청원 , 찬성한청원 구분해주세요.. 디자이너의 요청
- 토큰 만료시 401줄때 무엇을 더 추가해서 주셔야해요 비번 틀릴때도 401이여서 이상해져요
- 이메일이 없는 학교를 봐선.. 이름은 넣어야할것같아요 중복방지
- api answer 은 동의하기랑 커멘트랑 분리가 안되었습니다
- comment 에서 admin이 쓴 댓글은 get이 안됍니다
- petition list data를 줄때 approve 한 사람도 주셔야해요
- admin이 댓글을 써도 answer이 null 입니다 고쳐주세요
- admin이 댓글을 쓰면 동의하기가 됩니다 동의하기 되는거 없애주세요

### ✅ Tasks

- [x] comment 넘겨줄때 userId 도 넘겨주셔야합니다 -> 삭제 버튼 띄울지 말지
- [x] 그러면 로그인 성공시 data 주는 값에 userId를 추가해주셔야합니다
- [x] comment 줄떄 어드민이 쓴건지 학생이 쓴건지 구별해주세욥
- [x] 마이 청원 -> 내가올린청원 , 찬성한청원 구분해주세요.. 디자이너의 요청
- [x] 토큰 만료시 401줄때 무엇을 더 추가해서 주셔야해요 비번 틀릴때도 401이여서 이상해져요
- [ ] 이메일이 없는 학교를 봐선.. 이름은 넣어야할것같아요 중복방지
- [x] petition list data를 줄때 approve 한 사람도 주셔야해요
- [x] admin이 댓글을 써도 answer이 null 입니다 고쳐주세요

~~approve cors 에러 해결해주세엽~~
~~admin이 댓글을 쓰면 동의하기가 됩니다 동의하기 되는거 없애주세요~~
~~api answer 은 동의하기랑 커멘트랑 분리가 안되었습니다 분리해주세요~~
~~comment 에서 admin이 쓴 댓글은 get이 안됍니다~~

**Comment by gimhanul** [comment]
도메인을 

approve - [학생] 동의
comment - [학생, 학생회] 댓글
answer - [학생회] 청원 답변

인 거 아시나여?

이럼 api answer는 동의하기랑 커멘트 분리가 필요없어짐니다...

**Comment by SEOKKAMONI** [comment]
아 !! 넵

**Comment by SEOKKAMONI** [comment]
아 그리고 그 그것도해주세요 로그인 승인 어드민 쪽에서 받기로한거욥

**Comment by gimhanul** [comment]
근데 그럼 이름만으로는 안 될 것 같은데
학생회 쪽에서 이름만 가지고 승인을 시켜주기 어려울 것 같아요
받는 정보를 추가해야 할 것 같고
그리고 기존에 있던 방식을 엎고 계속 갈 건지 아니면 학생회 승인 방식만 할건지에 대한 논의?가 필요한듯
기획 관련해서는 진유림한테 물어보면 됨니다
왜냐하면 이게 진유림 머리에서 나온 프로젝트임

**Comment by SEOKKAMONI** [comment]
넵

**Comment by gimhanul** [comment]
진유림이랑 얘기 다 되면 나랑도 공유해주고

에러는 code field 추가헀읍니다

<img width="222" alt="image" src="https://user-images.githubusercontent.com/80656733/220883054-91bb06db-0bbf-4607-aa67-2ab91450c426.png">

[여기](https://github.com/Bamdoliro/Stupetition-server/blob/develop/src/main/java/com/bamdoliro/stupetition/global/error/exception/ErrorCode.java)보고 쓰면 댐

**Comment by gimhanul** [comment]
근데 userId는 localStorage에서 관리해서 껄꺼름한 건 상관 없습니다
어차피 백엔드 내에서 본인 계정의 댓글인지 확인하고 지우기 때문에 딱히 boolean으로 return 할 필요는 없는 듯하네용

**Comment by SEOKKAMONI** [comment]
아 넵 !!

**Comment by gimhanul** [comment]
> petition list data를 줄때 approve 한 사람도 주셔야해요

이거 뭘 달라는 건지 명확하게 알려주세용

**Comment by SEOKKAMONI** [comment]
이거 지금 리스트 줄때 동의한사람 숫자 안주시고계심데 그 디테일에는 주고있는거 있잖아여..

**Comment by gimhanul** [comment]
자꾸 이슈 수정해서 틀린그림찾기 하게 하지 말고... 새 이슈달아주33....3..3.3...

**Comment by SEOKKAMONI** [comment]
넵

**Comment by gimhanul** [comment]
>  admin이 댓글을 쓰면 동의하기가 됩니다 동의하기 되는거 없애주세요
손수 테스트 했는데 안그럼 api는 문제없어욤

**Comment by SEOKKAMONI** [comment]
엣 !!!!1 그럼 다시 확인해보도록하겠습니다
