### ISSUE TITLE
새로 부탁드립니다

### ISSUE THREAD

**Issue by SEOKKAMONI** [Bamdoliro/stupetition-server#41]
### ✨ Describe

- admin이 댓글을 써도 answer이 null 입니다 고쳐주세요
- admin이 댓글을 쓰면 동의하기가 됩니다 동의하기 되는거 없애주세요
- approve cors 에러 해결해주세엽

### ✅ Tasks

- [ ] admin이 댓글을 써도 answer이 null 입니다 고쳐주세요
- [ ] admin이 댓글을 쓰면 동의하기가 됩니다 동의하기 되는거 없애주세요
- [ ] approve cors 에러 해결해주세엽

**Comment by gimhanul** [comment]
앞에 거 확인하새욤 ^^...
